import { Router } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import platformRouter from "./platform";
import usersRouter from "./users";
import partnersRouter from "./partners";
import organisationsRouter from "./organisations";
import brandRouter from "./brand";
import coursesRouter from "./courses";
import modulesRouter from "./modules";
import beatsRouter from "./beats";
import studioRouter from "./studio";
import sessionsRouter from "./sessions";
import assessmentsRouter from "./assessments";
import credentialsRouter from "./credentials";
import coachRouter from "./coach";
import analyticsRouter from "./analytics";
import reportsRouter from "./reports";
import enrolmentsRouter from "./enrolments";
import discussionsRouter from "./discussions";
import announcementsRouter from "./announcements";
import assignmentsRouter from "./assignments";
import gradebookRouter from "./gradebook";
import calendarRouter from "./calendar";
import pagesRouter from "./pages";
import groupsRouter from "./groups";
import notificationsRouter from "./notifications";
import interactiveVideoRouter from "./interactive_video";
import learnRouter from "./learn";
import progressRouter from "./progress";
import activitiesRouter from "./activities";
import whatsappRouter from "./whatsapp";
import devRouter from "./dev";

const router = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(platformRouter);
router.use(usersRouter);
router.use(partnersRouter);
router.use(organisationsRouter);
router.use(brandRouter);
router.use(coursesRouter);
router.use(modulesRouter);
router.use(beatsRouter);
router.use(studioRouter);
router.use(sessionsRouter);
router.use(assessmentsRouter);
router.use(credentialsRouter);
router.use(coachRouter);
router.use(analyticsRouter);
router.use(reportsRouter);
router.use(enrolmentsRouter);
router.use(discussionsRouter);
router.use(announcementsRouter);
router.use(assignmentsRouter);
router.use(gradebookRouter);
router.use(calendarRouter);
router.use(pagesRouter);
router.use(groupsRouter);
router.use(notificationsRouter);
router.use(interactiveVideoRouter);
router.use(learnRouter);
router.use(progressRouter);
router.use(activitiesRouter);
router.use(whatsappRouter);
router.use(devRouter);

export default router;
